FROM dockerhub.tax.service.gov.uk/golang:1.15-alpine3.14 AS base
RUN apk add --no-cache \
    shadow~=4.8 \
    bash~=5.1
# UID of current user who runs the build
ARG user_id
# GID of current user who runs the build
ARG group_id
# HOME of current user who runs the build
ARG home
# change GID for dialout group which collides with MacOS staff GID (20) and
# create group and user to match permmisions of current who runs the build
ARG workdir
WORKDIR ${workdir}
COPY . .

RUN awk -F: '{print $3}' /etc/group | grep -x ${group_id} || \
    addgroup -S -g "${group_id}" union
RUN test -d "${home}" || mkdir -p "${home}"
RUN awk -F: '{print $3}' /etc/passwd | grep -x ${user_id} || \
    adduser -S -u "${user_id}" -h "${home}" -s "/bin/bash" -g ${group_id} builder
RUN chown -R ${user_id}:${group_id} "${workdir}"

FROM base AS gofmt
ENTRYPOINT [ "/usr/local/go/bin/gofmt" ]

FROM base AS go
ENV CGO_ENABLED=0
COPY go.mod go.sum ${workdir}/
ENV GOPROXY="https://artefacts.tax.service.gov.uk/artifactory/go-packages/"
RUN go mod download
ENTRYPOINT [ "/usr/local/go/bin/go" ]

FROM go AS golangci-lint
ENV GOLANGCI_LINT_VERSION=1.41.1
SHELL [ "/bin/bash", "-euo", "pipefail", "-c" ]
RUN wget -qO- "https://github.com/golangci/golangci-lint/releases/download/v${GOLANGCI_LINT_VERSION}/golangci-lint-${GOLANGCI_LINT_VERSION}-linux-amd64.tar.gz" \
    | tar -xzv -C /bin --strip-components=1 "golangci-lint-${GOLANGCI_LINT_VERSION}-linux-amd64/golangci-lint"
USER ${user_id}
ENTRYPOINT [ "/bin/golangci-lint" ]
